
elendev_roxyfileman_conf:
    path:     /resources/conf.json
    defaults: { _controller: ElendevRoxyFilemanBundle:Conf:conf }

elendev_roxyfileman_index:
    path:     /resources/index.html
    defaults: { _controller: ElendevRoxyFilemanBundle:Resources:resource, file: 'index.html' }

elendev_roxyfileman_resource:
    path:     /resources/{file}
    defaults: { _controller: ElendevRoxyFilemanBundle:Resources:resource }
    requirements:
        file: '[a-zA-Z0-9\-\/\._]+\.(?:css|html|js|json|gif|png)'

elendev_roxyfileman_dir_list:
    path:     /api/dirList
    defaults: { _controller: ElendevRoxyFilemanBundle:Directory:dirList }

elendev_roxyfileman_create_dir:
    path:     /api/createDir
    defaults: { _controller: ElendevRoxyFilemanBundle:Directory:createDir }

elendev_roxyfileman_delete_dir:
    path:     /api/deleteDir
    defaults: { _controller: ElendevRoxyFilemanBundle:Directory:deleteDir }

elendev_roxyfileman_move_dir:
    path:     /api/moveDir
    defaults: { _controller: ElendevRoxyFilemanBundle:Directory:moveDir }

elendev_roxyfileman_copy_dir:
    path:     /api/copyDir
    defaults: { _controller: ElendevRoxyFilemanBundle:Directory:copyDir }

elendev_roxyfileman_rename_dir:
    path:     /api/renameDir
    defaults: { _controller: ElendevRoxyFilemanBundle:Directory:renameDir }

elendev_roxyfileman_file_list:
    path:     /api/fileList
    defaults: { _controller: ElendevRoxyFilemanBundle:Directory:fileList }

elendev_roxyfileman_upload:
    path:     /api/upload
    defaults: { _controller: ElendevRoxyFilemanBundle:Directory:upload }

elendev_roxyfileman_download:
    path:     /api/download
    defaults: { _controller: ElendevRoxyFilemanBundle:Directory:download }

elendev_roxyfileman_download_dir:
    path:     /api/downloadDir
    defaults: { _controller: ElendevRoxyFilemanBundle:Directory:downloadDir }

elendev_roxyfileman_delete_file:
    path:     /api/deleteFile
    defaults: { _controller: ElendevRoxyFilemanBundle:Directory:deleteFile }

elendev_roxyfileman_move_file:
    path:     /api/moveFile
    defaults: { _controller: ElendevRoxyFilemanBundle:Directory:moveFile }

elendev_roxyfileman_copy_file:
    path:     /api/copyFile
    defaults: { _controller: ElendevRoxyFilemanBundle:Directory:copyFile }

elendev_roxyfileman_rename_file:
    path:     /api/renameFile
    defaults: { _controller: ElendevRoxyFilemanBundle:Directory:renameFile }

elendev_roxyfileman_generate_thumb:
    path:     /api/generateThumb
    defaults: { _controller: ElendevRoxyFilemanBundle:Directory:generateThumb }

